repos:
  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: Update pre-commit hooks
        entry: pwsh -c "pre-commit autoupdate; git add .pre-commit-config.yaml"
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: make-scripts-executable
        name: Make script files executable
        entry: bash -c 'git add --chmod=+x qi.bash qbt-nox-static.bash qbittorrent-nox-static.sh'
        language: system
        files: '(qi\.bash|qbt-nox-static\.bash|qbittorrent-nox-static\.sh)$'
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^(docs/|patch/)
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.15.1
    hooks:
      - id: zizmor

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"] # Optionally only show errors and warnings

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt
        args: ["-ci", "-sr", "-i", "0"]
