name: qb-amd64-patch
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        steps:
            - uses: actions/checkout@v2
            - run: apk add bash
            - run: bash qbittorrent-nox-static.sh
            - run: bash qbittorrent-nox-static.sh zlib
            - run: bash qbittorrent-nox-static.sh openssl
            # - run: bash qbittorrent-nox-static.sh icu
            - run: bash qbittorrent-nox-static.sh boost
            # - run: bash qbittorrent-nox-static.sh libtorrent
            - run: bash qbittorrent-nox-static.sh libtorrent -pr userdocs/qbittorrent-nox-static
            - run: bash qbittorrent-nox-static.sh qtbase
            # - run: bash qbittorrent-nox-static.sh qtbase -i
            - run: bash qbittorrent-nox-static.sh qttools
            # - run: bash qbittorrent-nox-static.sh qbittorrent
            - run: bash qbittorrent-nox-static.sh qbittorrent -pr userdocs/qbittorrent-nox-static
            - name: Archive code coverage results
              uses: actions/upload-artifact@v2
              with:
                  name: qbittorrent-nox
                  path: qb-build/completed/qbittorrent-nox
