name: ci - checks
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  sh-checker:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # v0.9.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SHELLCHECK_OPTS: -e SC2034,SC1091 # It is possible to exclude some shellcheck warnings.
          SHFMT_OPTS: -ci -sr -i 0 # It is possible to pass arguments to shftm
        with:
          sh_checker_comment: true
          sh_checker_exclude: ""

  zizmor-checker:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Run zizmor ðŸŒˆ
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0

  editorconfig-checker:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: editorconfig-checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          runner_arch: ${{ runner.arch }}
        run: |
          case "${runner_arch}" in
            X86 | X64)
              arch="amd64"
              ;;
            ARM | ARM64)
              arch="arm64"
              ;;
          esac

          curl -Lo- "https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-${arch}.tar.gz" | tar xzf - --strip-components=1
          ./ec-linux-${arch} --exclude '^(docs/.*|patches/.*)$' | sed 's/\x1b\[[0-9;]*m//g' | { printf '%b\n' '```bash' >> "$GITHUB_STEP_SUMMARY"; tee -a "$GITHUB_STEP_SUMMARY"; printf '%b\n' '```' >> "$GITHUB_STEP_SUMMARY"; }
          exit_code=("${PIPESTATUS[0]}")
          # exit "${exit_code}"
